apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: aktivitet
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{ image }}
  port: 8080
  prometheus:
    enabled: false
    path: /metrics
  replicas:
    min: 2
    max: 3
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

  ingresses:
  {{ #each ingresses as |url| }}
    - {{ url }}
  {{ /each }}